### ISSUE TITLE
Outdated maps

### ISSUE THREAD

**Issue by adriennn** [TeemuKoivisto/map-of-finland#1]
The maps from datajournalismi are really old and lots of communes have merged in the last five years in Finland. The coastlines can be either loaded from the [EU environment agency](https://www.eea.europa.eu/data-and-maps/data/eea-coastline-for-analysis-1/gis-data/europe-coastline-shapefile) or from Syke's lapio [portal](http://paikkatieto.ymparisto.fi/lapio/lapio_flex.html) (Hydrogrfia > Merialuejako) but the Syke's map don't show the islands so ymmv.

**Comment by TeemuKoivisto** [comment]
@adriennn Hi and yeah, this is why I used only the datajournalismi map for cutting the borders. I guess I totally forgot to mention why I did it this way in the first place, my bad.

Hmm I could check if I can cut the borders with that `Europe coastline shapefile` map but I must say it *was* tricky and I'm not too keen to repeat that process of torturing myself with QGIS. I recently created the map of finnish electoral districts that are used in parliamentary elections which was not fun, not fun at all.

**Comment by adriennn** [comment]
Hello @TeemuKoivisto and let me see if I can make a quick howto so you'll see it's really easy to do. But basically, you just take the Europe coastline and the MML Suomenvaltakunta polygon, intersect both to lessen the load on qgis. Filter out small polygons and use the Intersected layer to clip the MML Kunta map, and there you have it :)

**Comment by TeemuKoivisto** [comment]
@adriennn Sure but just to clarify I think the current map is up-to-date or at least it's based on the latest available on MML. The old 2013 map I used was only for clipping the coastline which I guess did it reasonably well. If and when municipality unifications happen in the future I hope I can just join them by hand with QGIS as the whole process to clip and remove polygons is way too much of a hassle. This reminded me that I should probably rebase the whole repo to get rid of the excess bloat generated by committing multiple versions of the maps to the git history.

But anyway thanks for your input, I hope you find this repo useful!
